# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: cat /dev/random
email: karim.dridi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  cat /dev/random | less
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kdridi.github.io" # the base hostname & protocol for your site
twitter_username: kdridi
github_username:  kdridi

# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# Author settings
author:
  name      : Karim DRIDI
  job       : Ingénieur Expert en NTIC
  bio       : "Enthousiaste, curieux, constamment à la recherche de nouveaux projets innovants et originaux."
  thumb     : /images/author.jpg
  email     : karim.dridi@gmail.com
  url       : http://kdridi.github.io
  github    : http://github.com/kdridi
  twitter   : http://twitter.com/kdridi
  facebook  : http://facebook.com/kdridi
  linkedin  : http://linkedin.com/in/karimdridi

# navbar pages
navbar:
  - slug: blog
    title: Blog
  - slug: cv-curriculum-vitae
    title: CV
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
